# Generated by Django 4.1.7 on 2023-02-24 08:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="sample text", verbose_name="Содержание"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.CharField(
                help_text="Краткое описание выполненной работы",
                max_length=255,
                verbose_name="Заголовок",
            ),
        ),
    ]
